### ISSUE TITLE
[tradefed] use bulk_create

### ISSUE THREAD

**Issue by chaws** [Linaro/squadplugins#24]
Maybe using `bulk_create` ([ref](https://docs.djangoproject.com/en/3.1/ref/models/querysets/#bulk-create)) in tradefed plugin will make it slightly faster if compared to making one trip to the DB per every test

**Comment by mwasilew** [comment]
It's already there: https://github.com/Linaro/squadplugins/blob/master/tradefed/__init__.py#L189
