### ISSUE TITLE
Detect kernel crashes/oopses/warnings from LAVA logs in squad

### ISSUE THREAD

**Issue by mwasilew** [Linaro/squadplugins#3]
Imported from https://projects.linaro.org/browse/QA-1673
The goal of this projest is to automatically detect any kernel problems from logs. It should be possible to do the parsing using regex. If that doesn't work, some more sophisticated log parsing should be applied.

Results might be reported in each TestRun as additional set of tests (separate test suite)

**Comment by chaws** [comment]
Closing this as got solved in https://github.com/Linaro/squad/pull/614 by the linux-log-parser plugin
